server:
  port: 9527

spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    mydept.serviceId: springcloud-dept   #真名
    mydept.path: /mydept/**              #代理名
  ignore-service: "*"                    #禁用所有微服务的真名
  prefix: /bgg                           #统一前缀

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: zuul-gateway
  company.name: bgg
  build.artifactId: $project.artifactId$
  build.version: $project.version$

