server:
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #禁用模板引擎的缓存
  messages:
    basename: i18n.Login  #国际化的默认名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql新的驱动包
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  dbcp2:
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 200                                  # 等待连接获取的最大超时时间
    validation-query: "SELECT 1"                          # 验证连接是否可用，使用的SQL语句
    test-while-idle: true                                 #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    test-on-borrow: false                                 #借出连接时不要测试，否则很影响性能

mybatis:
  type-aliases-package: com.bgg.springboot.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml              # mapper映射文件
